name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          run_install: |
            - args: [--frozen-lockfile, --no-verify-store-integrity]
      - run: |
          pnpm test
          pnpx codecov --disable=gcov
