name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Sources
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: '>=6'
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity, --no-optional]
    - name: Test
      run: |
        pnpm test
        pnpx codecov --disable=gcov
